version: 2
jobs:
  build:
    working_directory: ~/java102-repl
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run:
          command: |
            sudo apt-get install jq
            wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
      - checkout
      - restore_cache:
          key: java102-repl-{{ checksum "build.gradle" }}
      - run: ./gradlew clean build check jacocoTestReport
      - save_cache:
          paths:
            - ~/.m2
          key: java102-repl-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results/test
      - run: 
          command: |
            java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
      